include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    directives_ordering: true
    always_use_package_imports: true
    public_member_api_docs: false
    use_super_parameters: true

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
